language: php
sudo: false
dist: trusty

php:
  - '7.0'
  - '7.1'
  - nightly
  - hhvm

matrix:
  fast_finish: true
  allow_falures:
    - php: nightly
    - php: hhvm

cache:
  directories:
    - ./vendor

install:
  - composer self-update --no-interaction
  - composer install --no-interaction

script:
  - ./vendor/bin/phpunit
